local LSM = LibStub("LibSharedMedia-3.0")
local koKR, ruRU, zhCN, zhTW, western = LSM.LOCALE_BIT_koKR, LSM.LOCALE_BIT_ruRU, LSM.LOCALE_BIT_zhCN, LSM.LOCALE_BIT_zhTW, LSM.LOCALE_BIT_western

local MediaType_FONT = LSM.MediaType.FONT
local MediaType_STATUSBAR = LSM.MediaType.STATUSBAR

local MediaType_SOUND = LSM.MediaType.SOUND

LSM:Register(MediaType_FONT, "GothamNarrowUltra",       [[Interface\Addons\NaowhUI\Game\Shared\Media\Fonts\GothamNarrowUltra.ttf]],                           ruRU + western)
LSM:Register(MediaType_FONT, "GothamNarrowUltra",       [[Interface\Addons\NaowhUI\Game\Shared\Media\Fonts\GothamNarrowUltraAsia.ttf]],                       koKR + zhCN + zhTW)
LSM:Register(MediaType_FONT, "Naowh",                   [[Interface\Addons\NaowhUI\Game\Shared\Media\Fonts\Naowh.ttf]],                                       ruRU + western)
LSM:Register(MediaType_FONT, "Naowh",                   [[Interface\Addons\NaowhUI\Game\Shared\Media\Fonts\NaowhAsia.ttf]],                                   koKR + zhCN + zhTW)

LSM:Register(MediaType_STATUSBAR, "Melli",                  [[Interface\Addons\NaowhUI\Game\Shared\Media\Textures\Melli]])
LSM:Register(MediaType_STATUSBAR, "NaowhGradient",          [[Interface\Addons\NaowhUI\Game\Shared\Media\Textures\NaowhGradient]])
LSM:Register(MediaType_STATUSBAR, "NaowhLeft",              [[Interface\Addons\NaowhUI\Game\Shared\Media\Textures\NaowhLeft]])
LSM:Register(MediaType_STATUSBAR, "NaowhMouseover",         [[Interface\Addons\NaowhUI\Game\Shared\Media\Textures\NaowhMouseover]])
LSM:Register(MediaType_STATUSBAR, "NaowhMouseoverArrows",   [[Interface\Addons\NaowhUI\Game\Shared\Media\Textures\NaowhMouseoverArrows]])
LSM:Register(MediaType_STATUSBAR, "NaowhRight",             [[Interface\Addons\NaowhUI\Game\Shared\Media\Textures\NaowhRight]])

LSM:Register(MediaType_SOUND, "|cff0091ed1 -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\1.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed2 -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\2.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed3 -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\3.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed4 -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\4.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed5 -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\5.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed6 -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\6.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed7 -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\7.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed8 -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\8.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed9 -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\9.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed10 -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\10.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edAbsorb -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Absorb.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edAdd -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Add.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edAdds -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Adds.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edAoE -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\AoE.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edAvoid -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Avoid.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edBait -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Bait.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edBeam -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Beam.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edBehind -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Behind.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edBloodlust -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Bloodlust.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edBomb -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Bomb.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edBreath -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Breath.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edBuff -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Buff.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edCC -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\CC.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edCharge -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Charge.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edClear In -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\ClearIn.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edClear -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Clear.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edCollect -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Collect.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edCombat -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Combat.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edDance -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Dance.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edDebuff -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Debuff.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edDestroy -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Destroy.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edDispell -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Dispell.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edDodge Inc -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\DodgeInc.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edDodge -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Dodge.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edDot -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Dot.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edExternal -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\External.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edFixate -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Fixate.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edFreedom -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Freedom.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edFrontal -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Frontal.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edGreen -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Green.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edHide -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Hide.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edHigh Stacks -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\HighStacks.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edImmune -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Immune.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edIn -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\In.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edInc -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Inc.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edInside -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Inside.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edIntermission -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Intermission.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edKick -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Kick.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edKnock -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Knock.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edLeft -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Left.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edLinked -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Linked.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edLoS -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\LoS.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edMelee -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Melee.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edMount -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Mount.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edMove -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Move.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edNext -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Next.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edNuke -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Nuke.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edOrb -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Orb.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edOrbs -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Orbs.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edOut -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Out.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edOutrange -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Outrange.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edPersonal -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Personal.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edPot -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Pot.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edPull -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Pull.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edPush -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Push.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edRanged -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Ranged.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edReady -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Ready.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edRed -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Red.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edReflect -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Reflect.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edRight -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Right.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edRun -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Run.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edSac -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Sac.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edShield -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Shield.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edSoak -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Soak.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edSpike -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Spike.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edSpread -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Spread.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edStack -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Stack.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edStop -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Stop.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edStop Cast -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\StopCast.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edSwitch -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Switch.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edTaunt -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Taunt.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edTotem -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Totem.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edTrap -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Trap.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edTurn -Naowh|r", [[Interface\Addons\NaowhUI\Game\Shared\Media\Sounds\Turn.ogg]])